### ISSUE TITLE
Failed 

### ISSUE THREAD

**Issue by IbrahimovicAqram** [karma9874/AndroRAT#68] opened 2021-04-27 02:26 UTC
Failed to  create apk using ngrok  ,I am new in this field , please guide me  little

**Comment by bytesmalware** [comment] 2021-04-27 02:45
> Failed to  create apk using ngrok  ,I am new in this field , please guide me  little

![IMG-20210423-WA0003.jpg](https://user-images.githubusercontent.com/65878389/116177017-ba40a680-a730-11eb-8aa8-3eadb3e28e16.jpg)

**Comment by bytesmalware** [comment] 2021-04-27 02:46
> Failed to  create apk using ngrok  ,I am new in this field , please guide me  little

![IMG_20210427_081343.jpg](https://user-images.githubusercontent.com/65878389/116177064-ccbae000-a730-11eb-9a2d-4e0101874f24.jpg)

**Comment by bytesmalware** [comment] 2021-04-27 02:47
![IMG_20210427_081343.jpg](https://user-images.githubusercontent.com/65878389/116177161-f1af5300-a730-11eb-9da3-d499efbd0b2c.jpg)

**Comment by karma9874** [comment] 2021-04-27 16:15
Duplicate of #69

**Closed by karma9874** 2021-04-27 16:15 UTC
