### ISSUE TITLE
sign problem

### ISSUE THREAD

**Issue by WHITE-HAT786** [karma9874/AndroRAT#108] opened 2021-12-06 16:31 UTC
<a href="https://imgur.com/VHNZNHx.png">
  <img src="https://imgur.com/VHNZNHx.png" />
</a>
help please

**Comment by lazengann86** [comment] 2021-12-07 19:14
Same issue here. Anyone for a way around it?

**Comment by HenyPotter** [comment] 2021-12-11 10:05
Same issue here! I don't know where is the problem :/

**Comment by The3Hat** [comment] 2021-12-12 07:55
> [ ![](https://camo.githubusercontent.com/4ad6e658adb7de41f09b71ec07688cf1ffd7f884ef6fff6609a1b8fdd8476c41/68747470733a2f2f696d6775722e636f6d2f56484e5a4e48782e706e67) ](https://imgur.com/VHNZNHx.png) help please

Use openjdk-8-jdk

**Comment by The3Hat** [comment] 2021-12-12 07:56
i mean u must have java version 8 instead of 11

**Comment by karma9874** [comment] 2022-02-13 15:25
duplicate of #119

**Closed by karma9874** 2022-02-13 15:25 UTC

**Comment by WHITE-HAT786** [comment] 2022-04-03 14:34
My issue solved
 I changed by Java version
