### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder

### ISSUE THREAD

**Issue by Subass21** [karma9874/AndroRAT#105] opened 2021-11-20 06:33 UTC
when I try to install i get this error and I cant clear it :
i used latest version of java

Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
at s.Sign.addDigestsToManifest(Sign.java:108)
at s.Sign.sign(Sign.java:454)
at s.Sign.main(Sign.java:532)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 3 more

**Comment by Surya99941** [comment] 2021-11-20 06:36
I can confirm that same error is happening to me.

**My system details:**
Fedora 35
Java 11

**Comment by karma9874** [comment] 2021-11-20 07:03
You need to use java 8 for it to work.w

**Comment by HACKERgan** [comment] 2021-11-23 05:06
Hi bro I have problem can you help me please

**Comment by HACKERgan** [comment] 2021-11-23 05:06
![Uploading IMG_20211122_133613_173.jpg…]()

**Comment by IshpreetSingh8264** [comment] 2021-11-26 11:11
> You need to use java 8 for it to work.
please tell how to install it i will be very grateful thanks

**Comment by Surya99941** [comment] 2021-11-26 12:13
@IshpreetSingh8264, 
If you are using windows, you can follow this [guide](https://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jdk_install.html#CHDEBCCJ). 
If this guide seems hard, you can follow this [step-by-step guide](https://www.educba.com/install-java-8/). It's just downloading and installing the executable file, and then updating the path. 
If you are using multiple java versions (like 11 or 17) then install them in separate folder and update the path to the folder corresponding to the version you use.

In case of Linux like me, you should follow the distribution's guide.

**Comment by HACKERgan** [comment] 2021-11-27 01:24
Bro already installed hai Java 8

**Comment by IshpreetSingh8264** [comment] 2021-11-28 10:55
> @IshpreetSingh8264, If you are using windows, you can follow this [guide](https://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jdk_install.html#CHDEBCCJ). If this guide seems hard, you can follow this [step-by-step guide](https://www.educba.com/install-java-8/). It's just downloading and installing the executable file, and then updating the path. If you are using multiple java versions (like 11 or 17) then install them in separate folder and update the path to the folder corresponding to the version you use.
> 
> In case of Linux like me, you should follow the distribution's guide.

Umm im sorry if im disturbing or taking your time but can you please tell me how to do it on kali linux? coz yea idk how to install java 8 on kali linux 
Thx

**Comment by karma9874** [comment] 2022-02-13 15:24
duplicate of #119

**Closed by karma9874** 2022-02-13 15:24 UTC
