### ISSUE TITLE
Not able to build rat or even start listening for shell

### ISSUE THREAD

**Issue by aksploit** [karma9874/AndroRAT#59] opened 2021-03-18 17:45 UTC
Error

~/AndroRAT $ java --version
openjdk version 1.8.0_242
~/AndroRAT $ python3 androRAT.py --shell -i 127.0.0.1 -p 7676

                    _           _____         _______
    /\             | |         |  __ \     /\|__   __|
   /  \   _ __   __| |_ __ ___ | |__) |   /  \  | |
  / /\ \ | '_ \ / _` | '__/ _ \|  _  /   / /\ \ | |
 / ____ \| | | | (_| | | | (_) | | \ \  / ____ \| |
/_/    \_\_| |_|\__,_|_|  \___/|_|  \_\/_/    \_\_|

                                       - By karma9874

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AndroRAT/androRAT.py", line 45, in <module>
    get_shell(args.ip,args.port)
  File "/data/data/com.termux/files/home/AndroRAT/utils.py", line 310, in get_shell
    while t.isAlive(): animate("Waiting for Connections  ")
AttributeError: 'Thread' object has no attribute 'isAlive'
~/AndroRAT $

**Comment by karma9874** [comment] 2021-03-18 19:08
Duplicate of #60

**Closed by karma9874** 2021-03-18 19:08 UTC
